### ISSUE TITLE
Add multi-value fields to field--node--asu-repository-item.html.twig

### ISSUE THREAD

**Issue by dflitner** [asulibraries/islandora-repo#217] opened 2020-10-19 19:55 UTC
There's a chonky if statement in this twig to rewrite certain fields to inline lists.

We should review the other fields to see if there are any more to be added to this list (e.g. Language) and maybe refactor this to be a case statement instead.

For some reason, the rewrite isn't working for the Additional Memberships field so need to check that too.

**Comment by elizoller** [comment] 2021-01-08 18:44
@dflitner i'm not sure i'm following what the issue is here? can you elaborate?

**Comment by dflitner** [comment] 2021-01-08 19:18
Here is some context from Slack on the day I made this issue:
 
> Eli Zoller  12:25 PM
> and  on language, i should probably use a migration to swap the description and the label
> 
> Eli Zoller  12:26 PM
> it might require a little finagling of other config elsewhere but likely worth it. especially while we have little data migrated into production
> 
> Debbie Flitner  12:45 PM
> I'll make an issue for this but we also need to go through and figure out how many fields can have multiple entries and make sure we output them correctly. Right now we have if field is this or that or that etc and we should probably make it a case for ease of reading and adding more field names.
> 
> Eli Zoller  12:45 PM
> in what context? the field formatter?
> 
> Debbie Flitner  12:46 PM
> theme context
> [Screenshot](https://slack-files.com/TBY1XTCCR-F01CPSH0MKQ-2cc62c5107)
> 
> 12:47
> We have a twig for fields that rewrites certain ones to be a list, then there's css to add the / between list items
> 
> Eli Zoller  12:47 PM
> oh
> 12:47
> i see what you're saying
> 
> Debbie Flitner  12:47 PM
> So if we can have multiple genres, we need to add that to the list of field_names that's checked in the twig
> 
> Eli Zoller  12:47 PM
> ok, if you make an issue, i can verify. https://docs.google.com/spreadsheets/d/1pbX2LoTVwfuFQb55qUfh1rzTU69G21poZiLp3wasCo4/edit#gid=0 says whether a field is multi-valued or not
> 
> Debbie Flitner  12:47 PM
> I spotted it with language and then realized I have no idea how many fields can potentially have multiple values

This twig file has a lengthy if statement with certain fields hard-coded into it. I think the issue was that we needed to go through all of the fields and make sure they were added to that if statement (or change it to a case statement if that's easier/more clear) if they could have more than one value. I think it already has the most likely candidates for multi-value but if, for example, something had more than one language tagged, it wouldn't look like it's supposed to.

I should have tagged your message about with the spreadsheet in Slack so I would remember to go back and check the list to update this twig file.

There was some related discussion about a field formatter to change the URL to go to a faceted search instead of the taxonomy page but I think that was resolved with a module?

**Comment by elizoller** [comment] 2021-01-08 21:49
yeah - i **think** the faceted search stuff was resolved with #188 
i'll check the fields hard-coded in that template

**Comment by elizoller** [comment] 2021-01-08 21:51
sorry - which template are you referring to?

**Comment by dflitner** [comment] 2021-01-08 21:51
field--node--asu-repository-item.html.twig

**Comment by elizoller** [comment] 2021-01-08 22:11
would it also apply to field--node--asu-repository-item--full-metadata.html.twig?

**Comment by dflitner** [comment] 2021-01-08 22:14
No I don't think so. Because it's on the field template it should run whenever a field is displayed so it should already work on the full metadata display.

**Comment by elizoller** [comment] 2021-03-19 18:03
@dflitner does this still need work?

**Comment by dflitner** [comment] 2021-03-19 22:42
Yes, I haven't done anything on this since we talked about it. However I did find out that you can't use switch statements in Twig so we'll need to stick to the long if.
I wonder if we can get away with formatting it like:
```
{{ if (field_value == 'this thing we want') or
(field_value == 'this other thing') or
etc
```
and if that would make it more readable.

**Closed** 2021-07-06 21:00 UTC
Labels: theming/design
