### ISSUE TITLE
Derivatives issue.

### ISSUE THREAD

**Issue by merfimcfarland** [asulibraries/islandora-repo#560] opened 2022-08-24 00:32 UTC
These items won’t properly generate derivatives (thumbnails/viewers). Many of them have weird lines in place of the viewers:
https://keep.lib.asu.edu/items/167046 
https://keep.lib.asu.edu/items/167047
https://keep.lib.asu.edu/items/167048  
https://keep.lib.asu.edu/items/167049 
https://keep.lib.asu.edu/items/167050 
https://keep.lib.asu.edu/items/167051 
https://keep.lib.asu.edu/items/167052 
https://keep.lib.asu.edu/items/167053 
https://keep.lib.asu.edu/items/167054
https://keep.lib.asu.edu/items/167055  
https://keep.lib.asu.edu/items/167056 
https://keep.lib.asu.edu/items/167057 
https://keep.lib.asu.edu/items/167058 
https://keep.lib.asu.edu/items/167060 
https://keep.lib.asu.edu/items/164853

**Comment by seth-shaw-asu** [comment] 2022-08-26 23:01
It looks like most of these inappropriately applied the Thumbnail tag to the Original File. This, in some cases, caused the original file to be overwritten by the thumbnail derivative, effectively destroying it.

Original Files were corrupted by thumbnail generation due to thumbnail tag being applied to the original file and must be deleted and replaced:
- https://keep.lib.asu.edu/items/167046
- https://keep.lib.asu.edu/items/167051
- https://keep.lib.asu.edu/items/167052

Only needed the Thumbnails term removed and thumbnails regenerated (i.e. fixed):
- https://keep.lib.asu.edu/items/167047 (Mostly black rectangle)
- https://keep.lib.asu.edu/items/167048 (Mostly black rectangle)
- https://keep.lib.asu.edu/items/167049 (Mostly black rectangle)
- https://keep.lib.asu.edu/items/167050 (Mostly black rectangle)
- https://keep.lib.asu.edu/items/167054
- https://keep.lib.asu.edu/items/167055
- https://keep.lib.asu.edu/items/167056
- https://keep.lib.asu.edu/items/167057 (Black rectangle issue)
- https://keep.lib.asu.edu/items/167060

Items with the thumbnail issue, but are duplicates and should probably be deleted anyway:
- https://keep.lib.asu.edu/items/167053 - Duplicate of https://keep.lib.asu.edu/items/149139
- https://keep.lib.asu.edu/items/167058 - Duplicate of https://keep.lib.asu.edu/items/149109

Still broken:
- https://keep.lib.asu.edu/items/164853:
```
[2022-08-26 22:57:09] app.INFO: Imagemagick Command: {"cmd":"convert - -scale 800 jpeg:-"} []
[2022-08-26 22:57:10] app.ERROR: Process exited with non-zero code. {"exit_code":1,"stderr":"Error: Ignoring invalid annotation, output may be incorrect.\n+ ./base/gdevp14.c:1860: pdf14_put_image(): PDF14 device push/pop out of sync\nError: /unknownerror in /--pdfshowpage_finish--\nOperand stack:\n\nExecution stack:\n   %interp_exit   .runexec2   --nostringval--   pdfshowpage_finish   --nostringval--   2   %stopped_push   --nostringval--   pdfshowpage_finish   pdfshowpage_finish   false   1   %stopped_push   2046   1   3   %oparray_pop   2045   1   3   %oparray_pop   2026   1   3   %oparray_pop   2027   1   3   %oparray_pop   pdfshowpage_finish   pdfshowpage_finish   12   1   32   pdfshowpage_finish   %for_pos_int_continue   2030   1   7   %oparray_pop   pdfshowpage_finish   pdfshowpage_finish\nDictionary stack:\n   --dict:960/1684(ro)(G)--   --dict:1/20(G)--   --dict:82/200(L)--   --dict:82/200(L)--   --dict:133/256(ro)(G)--   --dict:313/450(ro)(G)--   --dict:34/64(L)--   --dict:6/9(L)--   --dict:8/20(L)--\nCurrent allocation mode is local\nGPL Ghostscript 9.26: Unrecoverable error, exit code 1\nconvert: no images defined `jpeg:-' @ error/convert.c/ConvertImageCommand/3301.\n"} []
[2022-08-26 22:57:10] app.ERROR: RuntimeException: {"exception":"[object] (RuntimeException(code: 500): Error: Ignoring invalid annotation, output may be incorrect.\n+ ./base/gdevp14.c:1860: pdf14_put_image(): PDF14 device push/pop out of sync\nError: /unknownerror in /--pdfshowpage_finish--\nOperand stack:\n\nExecution stack:\n   %interp_exit   .runexec2   --nostringval--   pdfshowpage_finish   --nostringval--   2   %stopped_push   --nostringval--   pdfshowpage_finish   pdfshowpage_finish   false   1   %stopped_push   2046   1   3   %oparray_pop   2045   1   3   %oparray_pop   2026   1   3   %oparray_pop   2027   1   3   %oparray_pop   pdfshowpage_finish   pdfshowpage_finish   12   1   32   pdfshowpage_finish   %for_pos_int_continue   2030   1   7   %oparray_pop   pdfshowpage_finish   pdfshowpage_finish\nDictionary stack:\n   --dict:960/1684(ro)(G)--   --dict:1/20(G)--   --dict:82/200(L)--   --dict:82/200(L)--   --dict:133/256(ro)(G)--   --dict:313/450(ro)(G)--   --dict:34/64(L)--   --dict:6/9(L)--   --dict:8/20(L)--\nCurrent allocation mode is local\nGPL Ghostscript 9.26: Unrecoverable error, exit code 1\nconvert: no images defined `jpeg:-' @ error/convert.c/ConvertImageCommand/3301.\n at /var/www/html/Crayfish/Houdini/vendor/islandora/crayfish-commons/CmdExecuteService.php:120)"} []
```
  Someone should simply manually make a thumbnail and upload it for this one.

Any chance you could address these before you go, @merfimcfarland?

**Closed as completed** 2023-08-24 21:08 UTC
Labels: task, AirTable
